---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
    spec:
      #  [WARN  tini (122)] Tini is not running as PID 1 and isn't registered as a child subreaper.
      #  Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
      #  To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
      #  Creating new 'host_docker' group with GID=999 with access to docker.sock
      #  Adding user 'jenkins' to group 'host_docker'
      #  touch: cannot touch '/var/jenkins_home/copy_reference_file.log': Permission denied
      #  Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
      # To fix this, we are running the jenkins process as root.
      securityContext:
        runAsUser: 0
      serviceAccountName: {{ .Values.rbac.serviceAccountName }}
      nodeSelector:
        node-type: dev
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.service.image.nameTag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 50000
        env:
        - name: INITIAL_START_DELAY
          value: "{{ .Values.service.initialStartDelay }}"
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 25
          timeoutSeconds: 5
          failureThreshold: 12
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 150
          timeoutSeconds: 5
          failureThreshold: 12
        volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
        {{- if eq .Values.minikube.enabled false }}
        # We expect an existing PVC unless running in minikube - then just use the docker volume
        - name: jenkinshome
          mountPath: "/var/jenkins_home"
        {{- end }}
        resources:
          # TODO: fill this in after load testing
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

      imagePullSecrets:
      - name: docker-registry-credentials

