---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.releaseName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.releaseName }}
spec:
  {{- if .Values.minikube.enabled }}
  type: NodePort
  {{- end }}
  ports:
  - port: 8080
    targetPort: 8080
    {{- if .Values.minikube.enabled }}
    nodePort: {{ .Values.minikube.nodePort }}
    {{- end }}
    protocol: TCP
    name: web
  - port: 50000
    targetPort: 50000
    protocol: TCP
    name: slave
  selector:
    app: {{ .Values.releaseName }}
